
apiVersion: v1
kind: Pod
metadata:
  name: alpine-github-actions
  labels:
    app: alpine-github-actions
  
spec:
 containers:
   - name: nginx
     image: sanojkv/app-github-actions:46e013cb977a170e4b722d77114459f99b624366