
apiVersion: v1
kind: Pod
metadata:
  name: alpine-github-actions
  labels:
    app: alpine-github-actions
  
spec:
 containers:
   - name: nginx
     image: sanojkv/app-github-actions:c947dcc8b54e0419f71fd4813582650962a8e0a7