
apiVersion: v1
kind: Pod
metadata:
  name: alpine-github-actions
  labels:
    app: alpine-github-actions
  
spec:
 containers:
   - name: nginx
     image: sanojkv/app-github-actions:17e2f507fa7b198a635e56337c1b50748a2b935c