name: CICD pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ./build.sh

  notify:
    needs: build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build failed"