name: CICD pipeline
on: 
    push:
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: npm test
      continue-on-error: true

    - name: Upload logs
      run: echo "Uploading logs"