name: CICD pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm test

  deploy:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - run: ./deploy.sh